{{- if .Values.infra.postgres.enabled }}
# Simple deployment for User DB - in real Prod use StatefulSet or Managed SQL
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-user
  template:
    metadata:
      labels:
        app: postgres-user
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - name: POSTGRES_USER
          value: "user"
        - name: POSTGRES_PASSWORD
          value: "password"
        - name: POSTGRES_DB
          value: "user_db"
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-user
spec:
  ports:
  - port: 5432
  selector:
    app: postgres-user
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-product
  template:
    metadata:
      labels:
        app: postgres-product
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - name: POSTGRES_USER
          value: "user"
        - name: POSTGRES_PASSWORD
          value: "password"
        - name: POSTGRES_DB
          value: "product_db"
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-product
spec:
  ports:
  - port: 5432
  selector:
    app: postgres-product
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-order
  template:
    metadata:
      labels:
        app: postgres-order
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - name: POSTGRES_USER
          value: "user"
        - name: POSTGRES_PASSWORD
          value: "password"
        - name: POSTGRES_DB
          value: "order_db"
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-order
spec:
  ports:
  - port: 5432
  selector:
    app: postgres-order
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-cart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-cart
  template:
    metadata:
      labels:
        app: postgres-cart
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - name: POSTGRES_USER
          value: "user"
        - name: POSTGRES_PASSWORD
          value: "password"
        - name: POSTGRES_DB
          value: "cart_db"
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-cart
spec:
  ports:
  - port: 5432
  selector:
    app: postgres-cart
{{- end }}
